### ISSUE TITLE
[FeedBack]: Faute dans le titre du mail

### ISSUE THREAD

**Issue by neozias** [Paladium-Developpement/Modded-Issue#1]
### Pseudo InGame

Neozias

### Nom de la feature

Mail Boutique

### Retour sur la Feature

![image](https://user-images.githubusercontent.com/56560980/182634015-0ff10748-3a93-4ba8-aa65-30802d40b3a6.png)
Faute d'ortographe, "inconnue" et non "inconnu"

**Comment by goldorak85** [comment]
Correctif appliqué, en attente de la mise en prod
