### ISSUE TITLE
[Bug]: Duplication via le /kit

### ISSUE THREAD

**Issue by Askiph** [Paladium-Developpement/Modded-Issue#11]
### Pseudo InGame

Askiph

### Que s'est-il passé ?

On peut retirer les item du /kit en utilisant les bouton en dessous de l'interface

![a](https://user-images.githubusercontent.com/53281382/182689360-0b54fd0e-179d-46e8-ae9f-4bf5ae8115ac.png)

### Serveur

Professionnel

**Comment by goldorak85** [comment]
Bug fix
