### ISSUE TITLE
[Bug]: Construction create clear au clear lag

### ISSUE THREAD

**Issue by Greenwich31** [Paladium-Developpement/Modded-Issue#14]
### Pseudo InGame

GreenwichI

### Que s'est-il passé ?

J'ai lancé un moulin create et alors qu'il était en mouvement un clear lag a clear toute la structure qui était en mouvement.

**Comment by goldorak85** [comment]
Ce bug ne se produit uniquement en SOLO, le serveur n'as pas ce problème, Et nous ne pouvons pas edit la config dans l'état actuelle du monde solo.
