### ISSUE TITLE
[Bug]: Pas de renvoi au site depuis le launcher

### ISSUE THREAD

**Issue by AngeDechue** [Paladium-Developpement/Modded-Issue#15]
### Pseudo InGame

AngeDechue

### Que s'est-il passé ?

Sur la page principale du launcher, lorsque l'on clique sur **Buy a server** ou **Shop**, on n'est pas renvoyé sur le site Modded mais sur la page principale de Google

### Qu'aurait-il dû arriver ?

Renvoyé sur les pages associées ou au moins sur le site Modded

**Comment by goldorak85** [comment]
Hello, Cela sera fix avec l'arrivé de la refonte du main menu :)

**Comment by goldorak85** [comment]
Fix
