### ISSUE TITLE
[Site]: Fautes dans la FAQ

### ISSUE THREAD

**Issue by neozias** [Paladium-Developpement/Modded-Issue#21]
### Pseudo InGame

Neozias

### Que s'est-il passé ?

Il y a quelques fautes dans la FAQ
![image](https://user-images.githubusercontent.com/56560980/182846201-e696a831-c4b9-4d90-8c2c-2ade0d55f6a9.png)

### URL de la page

https://modded.fr/faq

**Comment by goldorak85** [comment]
fix
