### ISSUE TITLE
[Site]: Couleurs des grades non correspondantes

### ISSUE THREAD

**Issue by neozias** [Paladium-Developpement/Modded-Issue#23]
### Pseudo InGame

Neozias

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/56560980/182846646-048fcbb9-d2fc-4552-9e99-8a2f4048e1b8.png)
La le grade jetpack est en jaune au lieu d'être dans sa couleur (le rouge)

### URL de la page

https://modded.fr/dashboard/me

### Navigateur internet

firefox

**Comment by FaustinM** [comment]
Fix https://github.com/Paladium-Developpement/modded-frontend/commit/905d79141a79724504e57aecdf65909864fa4c2a
