### ISSUE TITLE
[FeedBack]: Affichage menu principal

### ISSUE THREAD

**Issue by neozias** [Paladium-Developpement/Modded-Issue#3]
### Pseudo InGame

Neozias

### Nom de la feature

Main Menu

### Retour sur la Feature

![image](https://user-images.githubusercontent.com/56560980/182634712-eec593f4-4259-4645-8d21-623e2b98119e.png)
Des genre de Bords gris autour des carrés blancs + le "buy a server" qui est aligné étrangement

**Comment by goldorak85** [comment]
fix
