### ISSUE TITLE
[Site]: Copyright

### ISSUE THREAD

**Issue by EttudyOff** [Paladium-Developpement/Modded-Issue#31]
### Pseudo InGame

Ettudy

### Que s'est-il passé ?

Lors d'un mail de vérification, une petite erreur d'année xD

![Capture](https://user-images.githubusercontent.com/110555976/183038361-9152dc26-fd35-450f-bc71-9e174704ad98.PNG)

### Qu'aurait-il dû arriver ?

Copyright 2022

**Comment by goldorak85** [comment]
Fix
