### ISSUE TITLE
[Bug]: Problème de chargement des mods

### ISSUE THREAD

**Issue by Greenwich31** [Paladium-Developpement/Modded-Issue#4]
### Pseudo InGame

GreenwichI

### Que s'est-il passé ?

A chaque fois que je lance mon jeu une erreur apparait directement : 
![image](https://user-images.githubusercontent.com/105000230/182649369-7097a706-b8d4-4585-a9c9-3597759d0813.png)
J'ai essayé de supprimer le .modded et de relancer mais le problème persiste. 

Voici le crash report :
[crash report modded 1.txt](https://github.com/Paladium-Developpement/Modded-Issue/files/9252973/crash.report.modded.1.txt)

**Comment by goldorak85** [comment]
Un patch, viens d'être déployé avec de corriger le problèmes, cela peut éventuellement provoqué un nouveau, problème, En cas de problème, envoyé moi a nouveaux les logs.

**Comment by goldorak85** [comment]
Les logs on été transmise a @Chaika9

**Comment by goldorak85** [comment]
Problème fix !
