### ISSUE TITLE
[Bug]: Fond launcher

### ISSUE THREAD

**Issue by Agrausfr** [Paladium-Developpement/Modded-Issue#43]
### Pseudo InGame

Agraus

### Que s'est-il passé ?

Comportement bizzare font launcher
https://clips.twitch.tv/PoliteGlutenFreeDragonflySpicyBoy-3LXxycikuRoCR2y1

**Comment by goldorak85** [comment]
Hello, Cela sera fix avec l'arrivé de la refonte du main menu :)

**Comment by goldorak85** [comment]
Fix
