### ISSUE TITLE
[Bug]: Respawn après déconnexion Serveur Pro

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Modded-Issue#5]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Je me suis déconnecté à un endroit x mais en reconnectant je me suis reconnecté au spawn du world (sans être mort) 

### Serveur

Professionnel

**Comment by goldorak85** [comment]
Un patch de la sync a été appliqué, il sera déployé au prochain restart
