### ISSUE TITLE
[Bug]: Bug Inventaire 

### ISSUE THREAD

**Issue by Agrausfr** [Paladium-Developpement/Modded-Issue#55]
### Pseudo InGame

Agraus

### Que s'est-il passé ?

Un item change en fonction su serveur
![2022-08-13_19 01 21](https://user-images.githubusercontent.com/87886668/184503785-e7dc0b90-ba29-4783-adaf-9354700173c4.png)
![2022-08-13_18 58 25](https://user-images.githubusercontent.com/87886668/184503794-39d1d10b-ce99-4f80-b34c-d9271252a636.png)

**Comment by Agrausfr** [comment]
Pour plus de précisions sur certains services je n'est pas le livre bleu

**Comment by Agrausfr** [comment]
Et je n'est aucune idée de comment j'ai reçu ces 2 livres

**Comment by goldorak85** [comment]
Bug fix
