### ISSUE TITLE
[Bug]: Bug réapparition au dernier lit utilisé 

### ISSUE THREAD

**Issue by SirDoudou** [Paladium-Developpement/Modded-Issue#58]
### Pseudo InGame

SirDoudou

### Que s'est-il passé ?

Lorsque que le joueur meure et qu'il a un dormit dans un lit pour définir son point d'apparition, il ne réapparait pas a se même lit mais au point d'apparition du monde.

### Qu'aurait-il dû arriver ?

Le joueur aurait du réapparaitre a l'emplacement de son lit.

**Comment by goldorak85** [comment]
Bug fix
