### ISSUE TITLE
[Bug]: Wand ne marche sur un serveur multijoueur 

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Modded-Issue#6]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

A moins qu'il y a un truc qui m'échappe, je n'arrive pas à utiliser la wand de Construction Wand. 

En solo, ça marche très bien, mais en multi moi et la personne qui était sur mon serveur n'arrivons pas à l'utiliser pour construire.

https://imgur.com/a/sGnmdvX

### Serveur

Professionnel

**Comment by goldorak85** [comment]
bug fix
