### ISSUE TITLE
[Bug]: Impossibilité de rajouté des mods clientside suplementaires (Mini Map, Jade, Jei addons, ...)

### ISSUE THREAD

**Issue by SirDoudou** [Paladium-Developpement/Modded-Issue#60]
### Pseudo InGame

SirDoudou

### Que s'est-il passé ?

L'utilisateur du launcher de Modded (Paladium Launcher) ne peut rajouté de mods clients (ClientSide mod)  supplémentaires aux mods étant téléchargé de base par ce même launcher car ils sont supprimés au lancement du jeu par le launcher.

### Qu'aurait-il dû arriver ?

Les mods n'aurait pas du être supprimés au lancement et être laissé pendant l'exécution.

Ils ont surement était supprimés par un système veillant a l'intégralité des fichiers ou par un possible AntiCheat destiné à la partie Paladium du launcher.

**Comment by goldorak85** [comment]
Non, en tant normal vous n'avez pas a ajouté de mods au jeu, ce comportement est tout a fait normal
