### ISSUE TITLE
[Bug]: Le propriétaire du serveur est en aventure après s'être connecté sur un serveur où il ne disposé pas de droit

### ISSUE THREAD

**Issue by SirDoudou** [Paladium-Developpement/Modded-Issue#61]
### Pseudo InGame

SirDoudou

### Que s'est-il passé ?

Le joueur et propriétaire du serveur se retrouve dans le mode de jeu aventure après s'être connecté sur un serveur où il était dans le mode de jeu aventure et s'être reconnecté sur son serveur.

### Qu'aurait-il dû arriver ?

Il aurait du resté dans le mode de jeu survie sur son serveur.

Se bug doit être surement causé a cause de la synchronisation de l'inventaire et autres données du joueurs qui doit aussi synchronisé son mode de jeu 

### Serveur

Expert

**Comment by goldorak85** [comment]
Bug fix
