### ISSUE TITLE
[Bug]: Knockback lorsqu'on tape un autre joueur même si le PvP est desactivé

### ISSUE THREAD

**Issue by SirDoudou** [Paladium-Developpement/Modded-Issue#63]
### Pseudo InGame

SirDoudou

### Que s'est-il passé ?

Lorsqu'un joueur tape un autre joueur, il lui met un effet de knockback alors que le PvP est desactivé.

### Qu'aurait-il dû arriver ?

Le joueur attaqué n'aurait pas du subir un effet de knockback

**Comment by goldorak85** [comment]
Bug Fix
