### ISSUE TITLE
[Site]: Etat lancement serveur après refresh page perte couleur bouton

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Modded-Issue#7]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Mon serveur était en lancement, au centre du bouton et allumé en bleu. Cependant quand j'ai quitté la page puis revenu dessus, le logo est redevenu gris. 
![image](https://user-images.githubusercontent.com/92928910/182660520-7416e47b-e09e-462a-adc0-92c62437fbb1.png)

### Qu'aurait-il dû arriver ?

Il faudrait en plus de garder la couleur, mettre des hovers autres que 
![image](https://user-images.githubusercontent.com/92928910/182660699-63c279dc-b8b6-48c7-9229-7cad9f1b67f9.png)
Du genre : 
- "Serveur éteint, lancez ici"
- "Lancement du serveur en cours"
- etc

**Comment by FaustinM** [comment]
Salut Akyso,

J'ai modifié le comportement du bouton, en rajoutant que tu l'as proposé des Tooltips, pour ce qui est de la couleur, je n'y touche pas pour l'instant (la lumière est éteinte => le serveur est éteint ou en train de s'éteindre, la lumière est allumé => le serveur s'allume ou est allumé).

Si ce n'est toujours pas clair n'hésite pas à rouvrir l'issue pour améliorer le comportement du switch (à voir pour changer sa couleur par exemple)

Faustin
