### ISSUE TITLE
[Bug]: Problème démarrage serveur

### ISSUE THREAD

**Issue by Lykeostv** [Paladium-Developpement/Modded-Issue#78]
### Pseudo InGame

Lykeos_tv

### Que s'est-il passé ?

**Suite à un changement d'offre de Expert à Professionnel :** 

Sur le site, le serveur est indiqué comme "allumé" : 
![image](https://user-images.githubusercontent.com/33295363/185765347-602ea1b2-e139-4575-9448-ebff32ca4fc6.png)
mais lorsque l'on essaye de se connecter au serveur en jeu, le serveur est considéré comme "éteint" : 
![image](https://user-images.githubusercontent.com/33295363/185765379-9373d923-6434-4290-85ba-f74cd27932b6.png)

PS : J'ai déjà essayé de refresh la page, ca m'affiche toujours le serveur allumé sur le site, et j'ai déjà relancé le  launcher mais toujours pareil.

### Qu'aurait-il dû arriver ?

On aurait pu se connecter au serveur.

**Comment by Lykeostv** [comment]
Petite update pour ça :
Quand hier j'ai start le serveur, il s'était mis en éteint, j'ai refresh le site il s'est mis en allumé, puis après en autre refresh se remet en éteint

**Comment by EttudyOff** [comment]
Nous avons exactement le même problème avec le serveur d’Alastor.
Nous allions faire une issue mais tu as été trop rapide.

**Comment by goldorak85** [comment]
Bug fix :)
