### ISSUE TITLE
[Site]: Mauvaise Icone

### ISSUE THREAD

**Issue by Agrausfr** [Paladium-Developpement/Modded-Issue#83]
### Pseudo InGame

Agraus

### Que s'est-il passé ?

Icone "RAM" au lieu d'une îcone CPU
![Capture d’écran 2022-09-01 à 20 33 48](https://user-images.githubusercontent.com/87886668/187987612-5e5e2e32-4818-4856-8266-f2c3ae56130a.png)

### URL de la page

https://modded.fr/servers

**Comment by FaustinM** [comment]
Corrigé
