### ISSUE TITLE
[Bug]: Bug de dupli avec botania

### ISSUE THREAD

**Issue by AngeDechue** [Paladium-Developpement/Modded-Issue#94]
### Pseudo InGame

AngeDechue

### Que s'est-il passé ?

Il est possible de dupliquer n'importe quel objet avec botania. Pour cela il faut:
Un Petal Apothecary, un sceau d'eau, une vigne et l'item à dupliquer

Je vais décrire ici le principe mais une vidéo suivera:

1. On place le Petal Apothecary et on y ajoute de l'eau.
2. On jette l'item à dupliquer
3. On jette la vigne ce qui nous rend l'objet mais le laisse en place dans le Petal Apothecary
4. On casse le Petal Apothecary

Et voilà on a dupliqué notre item

**vidéo temporaire**: https://youtu.be/vzG9ljU1fM0

### Qu'aurait-il dû arriver ?

L'item n'aurait pas du se dupliquer

**Comment by Y4nN0xX** [comment]
bonjour supprime ou on te raye de modded

**Comment by goldorak85** [comment]
Fix
